import { Component } from '@angular/core';

interface Faction {
  id: string;
  route: string;
  sigil: string;
  bookTitle: string;
  bookSubtitle: string;
  thaiTitle: string;
  cover: string;
  chapters: number;
  highlights: string[];
}

@Component({
  selector: 'app-landing',
  templateUrl: './landing.component.html',
  styleUrl: './landing.component.scss',
})
export class LandingComponent {
  readonly factions: Faction[] = [
    {
      id: 'dawi',
      route: '/dawi',
      sigil: '⚒',
      bookTitle: 'DAMMAZ KRON',
      bookSubtitle: 'A Dawi Chronicle',
      thaiTitle: 'พงศาวดารคนแคระ',
      cover: '/assets/dawi/dawi_cover.png',
      chapters: 9,
      highlights: ['Karaz Ankor', 'Book of Grudges', 'The Deeps'],
    },
    {
      id: 'empire',
      route: '/empire',
      sigil: '☄',
      bookTitle: 'THE EMPIRE',
      bookSubtitle: 'The Imperial Chronicle',
      thaiTitle: 'พงศาวดารจักรวรรดิมนุษย์',
      cover: '/assets/empire/empire_karl-franz.png',
      chapters: 10,
      highlights: ['Sigmar', 'Elector Counts', 'Steam Tank'],
    },
    {
      id: 'khorne',
      route: '/khorne',
      sigil: '☠',
      bookTitle: 'THE BLOOD CHRONICLE',
      bookSubtitle: 'A Khorne Chronicle',
      thaiTitle: 'พงศาวดารเทพแห่งสงคราม',
      cover: '/assets/khorne/khorne_cover.png',
      chapters: 9,
      highlights: ['Brass Citadel', 'Bloodletting', 'Blood Host'],
    },
    {
      id: 'high-elves',
      route: '/high-elves',
      sigil: '🏹',
      bookTitle: 'THE HIGH ELVES CHRONICLE',
      bookSubtitle: 'A High Elves Chronicle',
      thaiTitle: 'พงศาวดารแห่งอุลธูอัน',
      cover: '/assets/high-elves/high-elves_cover.png',
      chapters: 10,
      highlights: ['Ulthuan', 'Tyrion & Teclis', 'Magic & Dragons'],
    },
    {
      id: 'skaven',
      route: '/skaven',
      sigil: '🐀',
      bookTitle: 'THE SKAVEN CHRONICLE',
      bookSubtitle: 'A Skaven Chronicle',
      thaiTitle: 'พงศาวดารหนู Skaven',
      cover: '/assets/skaven/skaven_cover.png',
      chapters: 10,
      highlights: ['Under-Empire', 'Warpstone', 'Warlock Engineers'],
    },
    {
      id: 'grand-cathay',
      route: '/grand-cathay',
      sigil: '龍',
      bookTitle: 'THE GRAND CATHAY CHRONICLE',
      bookSubtitle: 'A Grand Cathay Chronicle',
      thaiTitle: 'พงศาวดารแห่งจักรวรรดิมังกรสวรรค์',
      cover: '/assets/grand-cathay/grand-cathay_cover.png',
      chapters: 10,
      highlights: ['Great Bastion', 'Harmony', 'Dragon Siblings'],
    },
    {
      id: 'kislev',
      route: '/kislev',
      sigil: '❄',
      bookTitle: 'THE KISLEV CHRONICLE',
      bookSubtitle: 'A Chronicle of the Motherland',
      thaiTitle: 'พงศาวดารแห่งดินแดนหิมะ Kislev',
      cover: '/assets/kislev/kislev_cover.png',
      chapters: 8,
      highlights: ['Ice Court', 'Ursun', 'War Bears'],
    },
    {
      id: 'beastmen',
      route: '/beastmen',
      sigil: '♉',
      bookTitle: 'THE BEASTMEN CHRONICLE',
      bookSubtitle: 'A Chronicle of the Brayherds',
      thaiTitle: 'พงศาวดารสัตว์แห่งป่าเถื่อน',
      cover: '/assets/beastmen/beastmen_cover.svg',
      chapters: 8,
      highlights: ['Herdstones', 'Ambush', 'Primal Fury'],
    },
    {
      id: 'bretonnia',
      route: '/bretonnia',
      sigil: '⚜',
      bookTitle: 'THE BRETONNIA CHRONICLE',
      bookSubtitle: 'A Chivalric Chronicle',
      thaiTitle: 'พงศาวดารอัศวินแห่ง Bretonnia',
      cover: '/assets/bretonnia/bretonnia_cover.svg',
      chapters: 8,
      highlights: ['The Lady', 'Knights', 'Peasant Bowmen'],
    },
    {
      id: 'chaos-dwarfs',
      route: '/chaos-dwarfs',
      sigil: '⛓',
      bookTitle: 'THE CHAOS DWARFS CHRONICLE',
      bookSubtitle: 'A Chronicle of Hashut',
      thaiTitle: 'พงศาวดารคนแคระเคออส',
      cover: '/assets/chaos-dwarfs/chaos-dwarfs_cover.svg',
      chapters: 8,
      highlights: ['Zharr-Naggrund', 'Infernal Engines', 'Hashut'],
    },
    {
      id: 'daemons-of-chaos',
      route: '/daemons-of-chaos',
      sigil: '✹',
      bookTitle: 'THE DAEMONS OF CHAOS CHRONICLE',
      bookSubtitle: 'A Chronicle of the Four Gods',
      thaiTitle: 'พงศาวดารปีศาจแห่งเคออส',
      cover: '/assets/daemons-of-chaos/daemons-of-chaos_cover.svg',
      chapters: 8,
      highlights: ['Daemon Prince', 'Chaos Gifts', 'Realms'],
    },
    {
      id: 'dark-elves',
      route: '/dark-elves',
      sigil: '◈',
      bookTitle: 'THE DARK ELVES CHRONICLE',
      bookSubtitle: 'A Chronicle of Naggaroth',
      thaiTitle: 'พงศาวดารเอลฟ์ทมิฬ',
      cover: '/assets/dark-elves/dark-elves_cover.svg',
      chapters: 8,
      highlights: ['Naggaroth', 'Black Arks', 'Malekith'],
    },
    {
      id: 'greenskins',
      route: '/greenskins',
      sigil: '✊',
      bookTitle: 'THE GREENSKINS CHRONICLE',
      bookSubtitle: 'A Chronicle of the Waaagh!',
      thaiTitle: 'พงศาวดาร Greenskins',
      cover: '/assets/greenskins/greenskins_cover.svg',
      chapters: 8,
      highlights: ['Waaagh!', 'Bosses', 'Savage Momentum'],
    },
    {
      id: 'lizardmen',
      route: '/lizardmen',
      sigil: '◉',
      bookTitle: 'THE LIZARDMEN CHRONICLE',
      bookSubtitle: 'A Chronicle of the Great Plan',
      thaiTitle: 'พงศาวดาร Lizardmen',
      cover: '/assets/lizardmen/lizardmen_cover.svg',
      chapters: 8,
      highlights: ['Lustria', 'Slann', 'Geomantic Web'],
    },
    {
      id: 'norsca',
      route: '/norsca',
      sigil: 'ᚾ',
      bookTitle: 'THE NORSCA CHRONICLE',
      bookSubtitle: 'A Chronicle of the Northern Tribes',
      thaiTitle: 'พงศาวดารชนเผ่า Norsca',
      cover: '/assets/norsca/norsca_cover.svg',
      chapters: 8,
      highlights: ['Monster Hunts', 'Raiders', 'Dark Gods'],
    },
    {
      id: 'nurgle',
      route: '/nurgle',
      sigil: '☣',
      bookTitle: 'THE NURGLE CHRONICLE',
      bookSubtitle: 'A Chronicle of Decay',
      thaiTitle: 'พงศาวดารเทพแห่งโรคา',
      cover: '/assets/nurgle/nurgle_cover.svg',
      chapters: 8,
      highlights: ['Plagues', 'Cycles', 'Garden of Nurgle'],
    },
    {
      id: 'ogre-kingdoms',
      route: '/ogre-kingdoms',
      sigil: '☉',
      bookTitle: 'THE OGRE KINGDOMS CHRONICLE',
      bookSubtitle: 'A Chronicle of the Great Maw',
      thaiTitle: 'พงศาวดารอาณาจักร Ogre',
      cover: '/assets/ogre-kingdoms/ogre-kingdoms_cover.svg',
      chapters: 8,
      highlights: ['Great Maw', 'Camps', 'Mercenaries'],
    },
    {
      id: 'slaanesh',
      route: '/slaanesh',
      sigil: '♢',
      bookTitle: 'THE SLAANESH CHRONICLE',
      bookSubtitle: 'A Chronicle of Excess',
      thaiTitle: 'พงศาวดารเทพแห่งความลุ่มหลง',
      cover: '/assets/slaanesh/slaanesh_cover.svg',
      chapters: 8,
      highlights: ['Seduction', 'Speed', 'Temptation'],
    },
    {
      id: 'tomb-kings',
      route: '/tomb-kings',
      sigil: '☥',
      bookTitle: 'THE TOMB KINGS CHRONICLE',
      bookSubtitle: 'A Chronicle of Nehekhara',
      thaiTitle: 'พงศาวดารราชันสุสาน',
      cover: '/assets/tomb-kings/tomb-kings_cover.svg',
      chapters: 8,
      highlights: ['Nehekhara', 'Dynasties', 'Constructs'],
    },
    {
      id: 'tzeentch',
      route: '/tzeentch',
      sigil: '✦',
      bookTitle: 'THE TZEENTCH CHRONICLE',
      bookSubtitle: 'A Chronicle of Change',
      thaiTitle: 'พงศาวดารเทพแห่งการเปลี่ยนแปลง',
      cover: '/assets/tzeentch/tzeentch_cover.svg',
      chapters: 8,
      highlights: ['Schemes', 'Barriers', 'Sorcery'],
    },
    {
      id: 'vampire-coast',
      route: '/vampire-coast',
      sigil: '☠',
      bookTitle: 'THE VAMPIRE COAST CHRONICLE',
      bookSubtitle: 'A Chronicle of Pirate Undeath',
      thaiTitle: 'พงศาวดารโจรสลัดผีดิบ',
      cover: '/assets/vampire-coast/vampire-coast_cover.svg',
      chapters: 8,
      highlights: ['Pirate Coves', 'Gunlines', 'Sea Monsters'],
    },
    {
      id: 'vampire-counts',
      route: '/vampire-counts',
      sigil: '☾',
      bookTitle: 'THE VAMPIRE COUNTS CHRONICLE',
      bookSubtitle: 'A Chronicle of Sylvania',
      thaiTitle: 'พงศาวดารแวมไพร์แห่ง Sylvania',
      cover: '/assets/vampire-counts/vampire-counts_cover.svg',
      chapters: 8,
      highlights: ['Sylvania', 'Necromancy', 'Bloodlines'],
    },
    {
      id: 'warriors-of-chaos',
      route: '/warriors-of-chaos',
      sigil: '✠',
      bookTitle: 'THE WARRIORS OF CHAOS CHRONICLE',
      bookSubtitle: 'A Chronicle of Champions',
      thaiTitle: 'พงศาวดารนักรบแห่งเคออส',
      cover: '/assets/warriors-of-chaos/warriors-of-chaos_cover.svg',
      chapters: 8,
      highlights: ['Dark Fortresses', 'Gifts', 'Warbands'],
    },
    {
      id: 'wood-elves',
      route: '/wood-elves',
      sigil: '☘',
      bookTitle: 'THE WOOD ELVES CHRONICLE',
      bookSubtitle: 'A Chronicle of Athel Loren',
      thaiTitle: 'พงศาวดารเอลฟ์แห่งพงไพร',
      cover: '/assets/wood-elves/wood-elves_cover.svg',
      chapters: 8,
      highlights: ['Athel Loren', 'Forest Spirits', 'Waywatchers'],
    },
  ];

  readonly featuredFactions = this.factions.slice(0, 6);

  readonly factionGroups = [
    {
      title: 'Core Chronicles',
      ids: ['dawi', 'empire', 'khorne', 'high-elves', 'skaven', 'grand-cathay', 'kislev'],
    },
    {
      title: 'Chaos & Dark Powers',
      ids: [
        'beastmen',
        'chaos-dwarfs',
        'daemons-of-chaos',
        'norsca',
        'nurgle',
        'slaanesh',
        'tzeentch',
        'warriors-of-chaos',
      ],
    },
    {
      title: 'Immortal Empires',
      ids: [
        'bretonnia',
        'dark-elves',
        'greenskins',
        'lizardmen',
        'ogre-kingdoms',
        'tomb-kings',
        'vampire-coast',
        'vampire-counts',
        'wood-elves',
      ],
    },
  ].map((group) => ({
    title: group.title,
    factions: group.ids
      .map((id) => this.factions.find((faction) => faction.id === id))
      .filter((faction): faction is Faction => Boolean(faction)),
  }));
}
